apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: hastiCluster
  region: ap-south-1

nodeGroups:
  - name: ng1
    instanceType: t2.micro
    desiredCapacity: 3
    ssh:
      publicKeyName: eks
  - name: ng2
    instanceType: t2.micro
    desiredCapacity: 2
    ssh:
      publicKeyName: eks